version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: smart-nginx
    ports:
      - "8080:80"  # Expose Nginx on localhost:8080
    volumes:
      - ./public:/var/www/html/public
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf # Custom Nginx config
    depends_on:
      - php-fpm
    networks:
      - smartnet

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-php
    volumes:
      - .:/var/www/html  # Mount the project directory
      - ./config/php/php.ini:/usr/local/etc/php/php.ini # Custom PHP configuration
      - ./var:/var/www/html/var  # Ensure var directory is writable
    environment:
      - DATABASE_URL=pgsql://smartdbuser:smartdbpassword@smart-api-db:5432/smartdb
    networks:
      - smartnet

  smart-api-db:
    image: postgres:15
    container_name: smart-api-db
    environment:
      POSTGRES_USER: smartdbuser
      POSTGRES_PASSWORD: smartdbpassword
      POSTGRES_DB: smartdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartnet

volumes:
  postgres_data:

networks:
  smartnet:
